version: 1
applications:
  - frontend:
      phases:
        preBuild:
          commands:
            - cd budolshap-0.1.0 && npm ci
            - cd budolshap-0.1.0 && npx prisma generate --schema=prisma/schema.prisma
        build:
          commands:
            - cd budolshap-0.1.0 && npm run build
      artifacts:
        baseDirectory: budolshap-0.1.0/.next
        files:
          - '**/*'
      cache:
        paths:
          - budolshap-0.1.0/node_modules/**/*
