version: 1
applications:
  - frontend:
      phases:
        preBuild:
          commands:
            - cd budolpay-0.1.0/apps/admin && npm ci
            - cd budolpay-0.1.0/apps/admin && npx prisma generate --schema=prisma/schema.prisma
        build:
          commands:
            - cd budolpay-0.1.0/apps/admin && npm run build
      artifacts:
        baseDirectory: budolpay-0.1.0/apps/admin/out
        files:
          - '**/*'
      cache:
        paths:
          - budolpay-0.1.0/apps/admin/node_modules/**/*
