import json

# Read the file generated by PowerShell
with open('budol-shap-task-17-raw.json', 'r', encoding='utf-16') as f:
    task_def = json.load(f)

# Remove attributes that are not accepted when registering a new task definition
keys_to_remove = ['taskDefinitionArn', 'revision', 'status', 'requiresAttributes', 'compatibilities', 'registeredAt', 'registeredBy']
for key in keys_to_remove:
    if key in task_def:
        del task_def[key]

# Add Lalamove credentials to the first container's environment variables
container = task_def['containerDefinitions'][0]
env_vars = container.get('environment', [])

lalamove_vars = {
    "LALAMOVE_CLIENT_ID": "pk_test_194aaadd2c47bb2aba81116193f223a8",
    "LALAMOVE_CLIENT_SECRET": "sk_test_v5EzWm+k5YscrCQbdqRrS9i2PBpmMwrv5sAMK5Ah4ieJ69Ytd2nCK4zABD/cp7O6",
    "LALAMOVE_ENV": "sandbox",
    "LALAMOVE_WEBHOOK_SECRET": "lalamove_webhook_secret_budolshap_2025",
    "ENABLE_LALAMOVE": "true",
    "NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME": "dasfwpg7x",
    "CLOUDINARY_API_KEY": "537684148625265",
    "CLOUDINARY_API_SECRET": "USb6SDEDehMLyw9_HlFC1wDqlDE",
    "PAYMENT_GATEWAY_URL": "https://api.budolpay.budol.duckdns.org",
    "PAYMONGO_PUBLIC_KEY": "pk_test_t9hevWGf7dhg5rN4KPgYr8j7",
    "PAYMONGO_SECRET_KEY": "sk_test_QknCY1gyNypmFp3XdnTgBMjL",
    "NEXT_PUBLIC_SITE_URL": "https://budolshap.duckdns.org"
}

# Update existing or add new
env_dict = {v['name']: v['value'] for v in env_vars}
env_dict.update(lalamove_vars)

container['environment'] = [{"name": k, "value": str(v)} for k, v in env_dict.items()]

# Save the updated task definition as UTF-8
with open('budol-shap-task-18-lalamove.json', 'w', encoding='utf-8') as f:
    json.dump(task_def, f, indent=4)

print("Saved budol-shap-task-18-lalamove.json")
