global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8000']

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8001']

  - job_name: 'wallet-service'
    static_configs:
      - targets: ['wallet-service:8002']

  - job_name: 'transaction-service'
    static_configs:
      - targets: ['transaction-service:8003']

  - job_name: 'payment-gateway'
    static_configs:
      - targets: ['payment-gateway:8004']

  - job_name: 'settlement-service'
    static_configs:
      - targets: ['settlement-service:8005']
