services:
  - type: web
    name: budol-id-sso
    env: node
    plan: free
    rootDir: budolID-0.1.0
    buildCommand: npm install && npx prisma generate
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: LOCAL_IP
        value: "0.0.0.0"
